plugins: rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - bin/*
    - lib/tasks/**/*
    - Gemfile
  NewCops: enable

Rails:
  Enabled: true

Gemspec/DependencyVersion:
  EnforcedStyle: forbidden

Layout/LineLength:
  Max: 100
  Exclude:
    - bin/**/*
    - config/**/*
    - test/**/*

Metrics/AbcSize:
  Max: 30
  Exclude:
    - test/**/*
Metrics/BlockLength:
  Max: 30
  Exclude:
    - lr_common_styles.gemspec
    - test/**/*

Metrics/ClassLength:
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Exclude:
    - test/**/*

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Exclude:
    - test/**/*

Style/Documentation:
  Exclude:
    - test/**/*

Style/FormatStringToken:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
