plugins: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'

Gemspec/DependencyVersion:
  EnforcedStyle: forbidden

Layout/LineLength:
  Max: 100
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - lr_common_styles.gemspec
    - 'test/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Exclude:
    - 'test/**/*'
