name: Release and Publish Gem
on:
  workflow_dispatch: {}

jobs:
  build:
    name: "Build gem package"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Git Information"
      id: gitinfo
      run: |
        echo name=${GITHUB_REF#refs/*/}       >> $GITHUB_OUTPUT
        echo branch=${GITHUB_REF#refs/heads/} >> $GITHUB_OUTPUT
        make tags                             >> $GITHUB_OUTPUT

    - name: "Publish gem"
      env:
        VERSION: ${{ steps.gitinfo.outputs.tag }}
      shell: "bash"
      run: "make publish"

    - name: "Create Release"
      id: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.gitinfo.outputs.tag }}
        body: ${{steps.github_release.outputs.changelog}}
        draft: false
        prerelease: false
        files: |
          lr_common_styles-${{ steps.gitinfo.outputs.version }}.gem 
