name: Release and Publish Gem
on:
  workflow_dispatch: {}

jobs:
  build:
    name: "Build gem package"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Git Information"
      id: gitinfo
      run: |
        echo name=${GITHUB_REF#refs/*/}       | tee -a $GITHUB_OUTPUT
        echo branch=${GITHUB_REF#refs/heads/} | tee -a $GITHUB_OUTPUT
        make tags                             | tee -a $GITHUB_OUTPUT

    - name: "Build gem"
      run: "make gem"

    - name: "Create Release"
      id: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Release ${{ steps.gitinfo.outputs.version }}
        name: Release ${{ steps.gitinfo.outputs.tag }}
        body: ${{steps.github_release.outputs.changelog}}
        draft: false
        prerelease: false
        files: |
          lr_common_styles-${{ steps.gitinfo.outputs.version }}.gem 

    - name: "Publish gem"
      run: "make publish"
